import { render, screen } from "@testing-library/react";
import { describe, expect, it } from "vitest";

import PathwayUiReviewPage, { metadata } from "@/app/review/pathway-ui/page";

describe("pathway UI review route", () => {
  it("assembles every shared framework element without clinical output", () => {
    render(<PathwayUiReviewPage />);

    expect(metadata.title).toBe("Pathway UI review");
    expect(
      screen.getByRole("heading", { name: "Shared pathway UI framework" }),
    ).toBeInTheDocument();
    expect(screen.getByText("UI review only — no clinical output")).toBeInTheDocument();
    expect(screen.getByRole("navigation", { name: "Assessment progress" })).toBeInTheDocument();
    expect(screen.getByRole("spinbutton", { name: /Example laboratory result/i })).toHaveValue(
      123.4,
    );
    expect(screen.getByRole("group", { name: /Major decision/ })).toBeInTheDocument();
    expect(screen.getByRole("group", { name: "Grouped symptom selection" })).toBeInTheDocument();
    expect(screen.getByRole("heading", { name: "Safety alerts" })).toBeInTheDocument();
    expect(screen.getByRole("heading", { name: "Monitoring timeline" })).toBeInTheDocument();
    expect(screen.queryByText("YSTHFT-HYPONATRAEMIA-EMERGENCY-V1")).not.toBeInTheDocument();
    expect(screen.getByRole("heading", { name: "Immediate actions" })).toBeInTheDocument();
    expect(
      screen.getByText("No actions are generated by the UI framework preview."),
    ).toBeInTheDocument();
  });
});
